"""add reminder tables

Revision ID: 59e68cff5f43
Revises: abc123performance
Create Date: 2026-03-09 14:31:10.446515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e68cff5f43'
down_revision: Union[str, Sequence[str], None] = 'abc123performance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_business_active_created', table_name='customers')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.alter_column('documents', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('documents', 'vat_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('documents', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('documents', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('7.5'))
    op.alter_column('documents', 'is_vatable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('documents', 'requires_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_documents_business_date', table_name='documents')
    op.drop_index('ix_documents_business_status', table_name='documents')
    op.drop_index('ix_documents_created_at_order', table_name='documents')
    op.drop_index('ix_invoice_items_invoice_sort', table_name='invoice_items')
    op.drop_index('ix_invoice_items_sort_order', table_name='invoice_items')
    op.drop_index('ix_invoices_business_status_created', table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_index('ix_invoices_issue_date', table_name='invoices')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_payment_date_order', table_name='payments')
    op.drop_index('ix_products_business_sku', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_sku_single', table_name='products')
    op.drop_index('ix_products_usage_count', table_name='products')
    op.drop_constraint('uq_products_business_sku', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_products_business_sku', 'products', ['business_id', 'sku'])
    op.create_index('ix_products_usage_count', 'products', ['usage_count'], unique=False)
    op.create_index('ix_products_sku_single', 'products', ['sku'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_business_sku', 'products', ['business_id', 'sku'], unique=True)
    op.create_index('ix_payments_payment_date_order', 'payments', ['payment_date'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_invoices_issue_date', 'invoices', ['issue_date'], unique=False)
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_invoices_business_status_created', 'invoices', ['business_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_invoice_items_sort_order', 'invoice_items', ['sort_order'], unique=False)
    op.create_index('ix_invoice_items_invoice_sort', 'invoice_items', ['invoice_id', 'sort_order'], unique=False)
    op.create_index('ix_documents_created_at_order', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_business_status', 'documents', ['business_id', 'status'], unique=False)
    op.create_index('ix_documents_business_date', 'documents', ['business_id', 'document_date'], unique=False)
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'requires_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'is_vatable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('documents', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('7.5'))
    op.alter_column('documents', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('documents', 'vat_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('documents', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_index('ix_customers_business_active_created', 'customers', ['business_id', 'is_active', 'created_at'], unique=False)
    # ### end Alembic commands ###
