"""verify_schema_sync

Revision ID: 91735bd7ea66
Revises: 001_add_ai_features
Create Date: 2026-04-21 20:35:07.656161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91735bd7ea66'
down_revision: Union[str, Sequence[str], None] = '001_add_ai_features'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_insights_business_dismissed', table_name='ai_insights')
    op.drop_index('ix_ai_insights_created_at', table_name='ai_insights')
    op.drop_index('ix_bank_reconciliations_created_at', table_name='bank_reconciliations')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_index('ix_expenses_date', table_name='expenses')
    op.drop_index('ix_expenses_recurring', table_name='expenses')
    op.alter_column('payment_links', 'token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('payment_links', 'paystack_ref',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('payment_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_payment_links_invoice', table_name='payment_links')
    op.drop_constraint('payment_links_token_key', 'payment_links', type_='unique')
    op.drop_index('ix_payment_links_token', table_name='payment_links')
    op.create_index(op.f('ix_payment_links_token'), 'payment_links', ['token'], unique=True)
    op.create_index(op.f('ix_payment_links_business_id'), 'payment_links', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_links_invoice_id'), 'payment_links', ['invoice_id'], unique=False)
    op.drop_column('payment_links', 'expires_at')
    op.alter_column('reminder_logs', 'rule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reminder_logs', 'customer_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reminder_logs', 'recipient_email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reminder_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_reminder_logs_business', table_name='reminder_logs')
    op.drop_index('ix_reminder_logs_dedup', table_name='reminder_logs')
    op.drop_index('ix_reminder_logs_invoice', table_name='reminder_logs')
    op.create_index(op.f('ix_reminder_logs_business_id'), 'reminder_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_invoice_id'), 'reminder_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_rule_id'), 'reminder_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_sent_date'), 'reminder_logs', ['sent_date'], unique=False)
    op.drop_constraint('reminder_logs_rule_id_fkey', 'reminder_logs', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_logs', 'reminder_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reminder_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_reminder_rules_business', table_name='reminder_rules')
    op.create_index(op.f('ix_reminder_rules_business_id'), 'reminder_rules', ['business_id'], unique=False)
    op.alter_column('sales_targets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_targets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_sales_target_business_year', 'sales_targets', type_='unique')
    op.create_index(op.f('ix_sales_targets_business_id'), 'sales_targets', ['business_id'], unique=False)
    op.create_unique_constraint('uq_sales_target_biz_year', 'sales_targets', ['business_id', 'year'])
    op.drop_index('ix_stock_movements_business_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_movement_date', table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_id', table_name='stock_movements')
    op.drop_constraint('stock_movements_product_id_fkey', 'stock_movements', type_='foreignkey')
    op.drop_constraint('stock_movements_invoice_id_fkey', 'stock_movements', type_='foreignkey')
    op.drop_constraint('stock_movements_business_id_fkey', 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: These three constraint names are unknown — downgrade will fail
    # Do not use alembic downgrade on this migration without fixing these first
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key('stock_movements_business_id_fkey', 'stock_movements', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('stock_movements_invoice_id_fkey', 'stock_movements', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('stock_movements_product_id_fkey', 'stock_movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_stock_movements_product_id', 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_movement_date', 'stock_movements', ['movement_date'], unique=False)
    op.create_index('ix_stock_movements_business_id', 'stock_movements', ['business_id'], unique=False)
    op.drop_constraint('uq_sales_target_biz_year', 'sales_targets', type_='unique')
    op.drop_index(op.f('ix_sales_targets_business_id'), table_name='sales_targets')
    op.create_unique_constraint('uq_sales_target_business_year', 'sales_targets', ['business_id', 'year'])
    op.alter_column('sales_targets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_targets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reminder_rules_business_id'), table_name='reminder_rules')
    op.create_index('ix_reminder_rules_business', 'reminder_rules', ['business_id'], unique=False)
    op.alter_column('reminder_rules', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_rules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'reminder_logs', type_='foreignkey')
    op.create_foreign_key('reminder_logs_rule_id_fkey', 'reminder_logs', 'reminder_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_reminder_logs_sent_date'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_rule_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_invoice_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_business_id'), table_name='reminder_logs')
    op.create_index('ix_reminder_logs_invoice', 'reminder_logs', ['invoice_id'], unique=False)
    op.create_index('ix_reminder_logs_dedup', 'reminder_logs', ['invoice_id', 'rule_id', 'sent_date'], unique=True)
    op.create_index('ix_reminder_logs_business', 'reminder_logs', ['business_id'], unique=False)
    op.alter_column('reminder_logs', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_logs', 'recipient_email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('reminder_logs', 'customer_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('reminder_logs', 'rule_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    op.add_column('payment_links', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payment_links_invoice_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_business_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_token'), table_name='payment_links')
    op.create_index('ix_payment_links_token', 'payment_links', ['token'], unique=False)
    op.create_unique_constraint('payment_links_token_key', 'payment_links', ['token'])
    op.create_index('ix_payment_links_invoice', 'payment_links', ['invoice_id'], unique=True)
    op.alter_column('payment_links', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_links', 'paystack_ref',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('payment_links', 'token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_index('ix_expenses_recurring', 'expenses', ['business_id', 'is_recurring', 'next_due_date'], unique=False)
    op.create_index('ix_expenses_date', 'expenses', ['business_id', 'expense_date'], unique=False)
    op.create_index('ix_expenses_category', 'expenses', ['business_id', 'category'], unique=False)
    op.create_index('ix_bank_reconciliations_created_at', 'bank_reconciliations', ['created_at'], unique=False)
    op.create_index('ix_ai_insights_created_at', 'ai_insights', ['created_at'], unique=False)
    op.create_index('ix_ai_insights_business_dismissed', 'ai_insights', ['business_id', 'is_dismissed', 'created_at'], unique=False)
    # ### end Alembic commands ###
